language: scala
scala:
- 2.11.11
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
git:
  submodules: false
before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: P9CaVw/axNlkr/9bry2/yyJpuUZ5cf4M2hBR5qtbLRlNwAawGiwIskxqF7+GL0NyuuwUdlgv0LMR7mmrMJQVJV7b2kHXPVPeFbjF6ImlwUuvBkbKrSCdsWqWwezAmsx2w5x/cCJjff7FOuZRE17n0SSa3zs8d3dMzUMwXQ+dxJHaCBivd+OX5n+N4tyu8XBR34HBCDE5RKaa6LkViHs4oIY771iNJNY+iwioPUA7WtAFKpchaEeV+609hyOKddYaeSPsKDajAGA/l6wwVuoPabSaNOdQLQNYpxtJoRUiSB3CIMx8hKsvI4uSV+I5EdoCjM7lHOxsmw+gccd3T5EJHrdpbRwvWsY4SrF9ysmjNb4SAnPpCySRZ0nKRMp6PHYkkdP1/MUGQH68qB5jgKDJzoZjpCf2ZamG8YiEWFzAO0hL6QjuMiSg+ITiRj6FjxGnIqkZbajOf9+ozFbTYs+U6wooUz6qUJwmhF+KPlE7lJsUURD9Y67Ri+N+bN56qdUgt3D3zePIAdShekqCSa4FSm4IJNh7inuPPLYBfgoe5R2BBKz2aOUhsGG4UMG2Qf5KPw6AHW8ElqWN+34TrFIBY+y3bFT6FVRP3Q+Fg8tcliH/DYADHPw8ZuqfVeUbR6EV7frzV2t1weLD1ftGZP/oYlTDGzhGHSpf1TBoNkOJbIA=
  app:
    master: htwg-morris
    development: travis-morris-test
  on:
    repo: LarsKnaack/de.htwg.wt.muehle
