language: scala
scala:
- 2.11.11
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
git:
  submodules: false
before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: dA/rMLHjjhgL88e53GM6Wvz4s3deJvPssnUarX1Xn4J4HJV6R4nnImZNPq/FEdhQeHUUsfHu967e0SH25P3RSc0cSX4uMOJ192pwFALw6m+hwwoy8JYh504c5w1eFeNccvcgvbgNtTrStrpnaGceid15YzFEQs7m3n6BkadDfQhRdXPgqw6fmVJ2O7bL0mEAT7zInSQHuiJOGhUCkJMxhqY//1+zi2ZUpWPCBpR+DLpuVQ5EtMDDnlnyz2lptpVvDWkCUzJA4MYuCGivxQF1Ybz4P611T3DaCQ2GSGOjCRBVz73a1/bKS/yYP5Nzrtq9WAY3+BOnQF26BKBPsE1AIXi+rAhtFF0xX/UbcQP1L1drNnxoF7/33Zqrg6TNnc5lekj8T6BCIemsilonQr2u3DQ0AK6zwwZx58E4pdGTQD3sW9pjYz8jyNcbp7qi00bDn2jKdU2JXW2pNfSwTuOn7xPDcpSRKQY477oz6p+O05/mVZvLsw31Qm6ug4v1r/72HJ+cdqp+aakxygN41MtRbaYJe9G/1lKGqwCCd6bWNqlWwELlEyxNygg5R5BnIbm9apFikj7rtwaYaFLzfYquRiVssBOI9fS68bHJyuWwHuvdITr2Ply0oKu104LWRlnDHh+T8tK8inval4Z0CXUizJNaYrTitYsBCdb1SlczuVc=
  app:
    master: htwg-morris
    development: travis-morris-test
  on:
    repo: LarsKnaack/de.htwg.wt.muehle
